---
title: "CAMS Dissertations: <br> A Dissertation in Geography (GEOG5957)"
author: "Roger Beecham"
date: "Tue 25th Jan 2022"
output:
  xaringan::moon_reader:
    css: [default, "slides-theme.css"]
    lib_dir: libs
    nature:
      ratio: '16:9'
      highlightStyle: github
      highlightLines: true
      slideNumberFormat: ''
      titleSlideClass: [center, middle]
---

```{r setup, include=FALSE, echo=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(comment = "")
library(tidyverse)
library(here)
library(knitr)
library(kableExtra)
```

## A Dissertation in Geography

--
.small-text[
> Involves some form of **spatial analysis** linked to any of the topics covered in the lectures and practical classes.
]
--
.tiny-text[
> Is **analytic** in nature, using any of the methods, tools and techniques covered in your Geography modules
]
--
.tiny-text[
> Uses **secondary data** from any of the broad type of sources that we have introduced.
]
--
.tiny-text[
> Represents a substantial piece of **academic research**, but can be carried out with input from a company or other external organisation.
]


???

Spatial analysis : ole of spatial location, scale in some process.
Analytic: applying data analysis techniques covered in Geog module
Secondary data analysis: repurposing data that already exists
Academic: important and useful to locate what you do within spatial analysis literature

---

## Areas of focus: technical and thematic

.pull-left[.small-font[**Techniques** <br>
* Spatial pattern analysis
* Time series analysis
* Network analysis
* Machine Learning
  + regression, decision trees, clustering
* Empirical modelling
  + ABMs/microsimulation
* Data visualisation
]]

.pull-right[.small-font[**Themes** <br>
* Demographics
* Housing markets
* Consumer analytics/profiling
* Network planning
* Targeted marketing / Response modelling
* Inequalities and accessibility
]]


???
Also technology : R, Python, others
---

## How to come up with an ideas

.small[
* Identify aspects of the course that have **interested you** and some of the readings that you have undertaken.  Are there aspects that you’d be able and **want to develop further**?

* Note some of the **methods and technologies** used -- could you apply these to a different study area or a slightly different problem?

* Is there an **interesting dataset** that you’d like to explore further?

* Is there a **particular issue** related to your home country or your previous study/employment that you could focus on
]

???
Pick interesting paper/study/analysis read?

---

## Overview of process

* Follow roughly the same format and timings as LUBS dissertations.

* You’re allocated a mentor who you will meet with 5-6 times for advice and guidance.

* You primarily **work independently** applying methods that you’ve previously been taught and learning new methods for yourself.

* Projects may be data-driven but **must be spatial in nature** and clearly related to academic and/or industry literature.

* Chance to work with new and exciting spatial data and apply advanced techniques that you've learnt 'in the trenches'

---

## CAMS Geography Dissertations

<!-- |    |                                              |
|-------------|--------------------------------------------------------------|
| Important   | .small-font[Worth 30 credits]                                             |
| Interesting | .small-font[Chance to study something that matters to you]                |
| Independent | .small-font[Opportunity to work on substantive piece of work on your own] |
| Initiative  | .small-font[Led by you]                                                   | -->


* **Important**  | .small-font[Worth 30 credits]

* **Interesting** | .small-font[Chance to study something that matters to you]

* **Independent** | .small-font[Opportunity to work on substantive piece of work on your own]

* **Initiative**  | .small-font[Led by you]
---
